function init(self)
	msg.post(".", "acquire_input_focus")
	self.is_debug = sys.get_engine_info().is_debug
	if self.is_debug then
		gameanalytics.setCustomDimension01("debug")
	else
		gameanalytics.setCustomDimension01("live")
	end
	print("Is Debug: " .. tostring(self.is_debug))
end

function on_input(self, action_id, action)
	if self.is_debug then
		if action_id == hash("overdraw") and action.released then
			msg.post("@render:", "toggle_overdraw")
		end
	end
end
