local counter = require "main.app.counter_screen.counter_screen"
local url = require "utils.url"

function init(self)
    url.set("counter", msg.url("."))
    counter.init(self)
end

function on_message(self, message_id, message)
    if message_id == hash("reload_ui") then
        counter.reload()
    end
end


function on_input(self, action_id, action)
    counter.on_input(self, action_id, action)
end
